config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'

  get 'about', to: 'pages#about'
  get 'terms', to: 'pages#terms'

  resource :contacts, only: [:new, :create], path_names: { new: '' }
  resources :articles do
    resources :comments, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { maximum: 140 }
  validates :text, presence: true, length: { in: 5..4000 }

  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :body, presence: true, length: { in: 5..4000 }
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :success, :danger, :info, :warning

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
    user_params.permit(:username, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit destroy]
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all
    @users = User.all
  end

  def new
    @article = Article.new
  end

  def show; end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    if @article.save
      redirect_to @article, success: 'Article create successfully'
    else
      render :new, danger: 'Article not created'
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article, success: 'Article updated successfully'
    else
      render :edit, danger: 'Article not updated'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path, success: 'Article delete successfully'
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]
  before_action :set_article, only: [:create, :destroy]

  def create
    @article.comments.create(author: current_user.username, body: comment_params[:body])
    redirect_to article_path(@article)
  end

  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new; end

  def create
    @contact = Contact.new(contact_params)

    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about; end

  def terms; end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/articles/_article.html.erb
  <article class="article">
  <section class="article_head">
    <h3><%= link_to article.title, article_path(article) %></h3>
       <span style="font-size: 75%; color: #2F4F4F">
         <div>
          Added at <%= article.created_at.to_date.strftime("%d %B, %Y") %> by <%= (@users.find(article.user_id)).username %>
         </div>
         <div>
            <% if user_signed_in? && article.user_id == current_user.id%>
              <%= link_to 'Edit', edit_article_path(article) %> |
              <%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%end%>
         </div>
       </span>

  <hr>
  </section>

  </article>
  

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
	<div class="alert alert-danger">
		<h5><%= pluralize(@article.errors.count, "Error") %> prohibited this article from being saved:</h5>
		<ul>
			<% @article.errors.full_messages.each do |message| %>
			<li><%= message%></li>
			<%end%>
		</ul>
	</div>
<%end%>

<%= form_with model: @article, local: true do |f| %>
	<div class="form-group">
		<%= f.label :title %><br>
		<%= f.text_field :title, class: "form-control"%>
	</div>

	<div class="form-group">
		<%= f.label :text %><br>
		<%= f.text_area :text, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.submit class: "btn btn-primary"%>
		<%= link_to "Back", articles_path, class: "btn btn-outline-secondary"%>
	</div>
<% end %>

app/views/articles/edit.html.erb
<h2>Edit article</h2>

<%= render 'form'%>

app/views/articles/index.html.erb
<h2>Articles</h2>
<br>

<%= render @articles%>

app/views/articles/new.html.erb
<h2><%= t('article.new_article') %></h2>

<%= render 'form'%>

app/views/articles/show.html.erb
<p><strong>Article: </strong><%= @article.title %></p>
<p><strong>Text: </strong>	<%= @article.text %></p>

<!-- For resource has assotiation defined use 'form_for([@document, @comment]) do |f|'
@article.comments.build return new object of the collection, but has not been saved -->

<h3>Comments</h3><br>
<%= render @article.comments %>

<h3>Add a comment</h3>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p><span style="font-size: 75%; color: #2F4F4F">
  <% if comment.body %>
  <%= comment.author %> said at <%= comment.created_at%>

    <% if user_signed_in? && comment.author == current_user.username  %>
    <%= link_to 'Delete', [comment.article, comment],
          method: :delete,
          data: { confirm: 'Are you sure?' } %>
      <%end %>
    <% end %>
</span></p>

<p><%= comment.body %></p>

<hr>

app/views/comments/_form.html.erb
<%= form_with(model: [@article, @article.comments.build]) do |f| %>
	<p>
<!--		<%#= f.label :comment %><br>-->
		<%= f.text_area :body, class: "form-control" %>
	</p>
  <br>
	<p>
		<%= f.submit class: "btn btn-primary"%>
		<%= link_to "Back", articles_path, class: "btn btn-outline-secondary"%>
	</p>
  <br>

<% end %>

app/views/contacts/create.html.erb
<p>Thanks!</p>

app/views/contacts/new.html.erb
<h2><%= t('contacts.contact_us') %></h2>
<%= form_for :contact, url: contacts_path do |f| %>
	
	<% if @contact && @contact.errors.any? %>
    <div>
        <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <%end%>
        </ul>
    </div>

	<% end %>
  <p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :message %><br>
		<%= f.text_area :message %>
	</p>
	<p>
		<%= f.submit 'Send message'%>
	</p>

<% end %>

app/views/layouts/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">SampleBlog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/terms">Terms</a>
        </li>
        <%if user_signed_in?%>
          <li class="nav-item">
            <%= link_to "Create Article", new_article_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.username%>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        <%else%>
          <li class="nav-item">
            <a class="nav-link disabled">Create Article</a>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= render "layouts/navbar" %>

    <div class="container">
      <div class="row">
        <div class="col-xs-12">

<!--           <p class="notice"><%#= notice %></p> -->
          <p class="alert"><%= alert %></p>
          <% flash.each do |name, message|%>
            <div class="alert alert-<%=name%>">
              <%=message%>
            </div>
          <%end%>

          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About us</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>

app/views/pages/terms.html.erb
<h2>Terms of Service</h2>
<p>Lorem ipsum dolor sit amet. </p>